#!/bin/sh

set -e

echo "Compile"

mkdir -p target/classes target/test-classes

javac -encoding "UTF-8" -d target/classes -classpath "target/classes;target/test-classes/" src/main/java/com/baldurtech/*.java
javac -encoding "UTF-8" -d target/test-classes -classpath "target/classes;target/test-classes/" src/main/test/com/baldurtech/*.java
echo "Compile done."
